cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'

brew 'ack'
brew 'awscli'
brew 'coreutils' # GNU core utilities (those that come with macOS are outdated)
brew 'jq'
brew 'openssl'
brew 'node'
brew 'wget'
brew 'zsh'
brew 'libyaml'
brew 'yarn'

cask 'dropbox'
cask 'google-chrome'
cask 'iterm2'
cask 'slack'
cask 'sequel-pro'
cask 'sublime-text'
cask 'vlc'
cask 'lastpass'
cask 'spotify'
cask 'phpstorm'
cask 'docker'
cask 'docker-toolbox'
cask 'tunnelblick'