cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'awscli'
brew 'coreutils' # GNU core utilities (those that come with macOS are outdated)
brew 'jq'
brew 'libyaml'
brew 'node'
brew 'openssl'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'vim', args: ['--override-system-vi']

cask 'docker'
cask 'docker-toolbox'
cask 'dropbox'
cask 'google-chrome'
cask 'iterm2'
cask 'lastpass'
cask 'phpstorm'
cask 'sequel-pro'
cask 'slack'
cask 'spectacle'
cask 'spectacle'
cask 'spotify'
cask 'sublime-text'
cask 'tunnelblick'
cask 'vlc'
